apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
  annotations:
    # Ensure secrets are created/updated before other resources
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    # Add checksum annotation to trigger pod restarts on secret changes
    checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}

type: Opaque
data:
  # API Configuration
  API_URL: {{ required "API URL is required" .Values.secrets.apiUrl | b64enc | quote }}
  API_KEY: {{ required "API key is required" .Values.secrets.apiKey | b64enc | quote }}
  
  # Authentication Configuration
  AUTH_TOKEN: {{ required "Authentication token is required" .Values.secrets.authToken | b64enc | quote }}
  
  # Integration API Keys
  CLAUDE_API_KEY: {{ required "Claude API key is required" .Values.secrets.claudeApiKey | b64enc | quote }}
  LINKEDIN_API_KEY: {{ required "LinkedIn API key is required" .Values.secrets.linkedinApiKey | b64enc | quote }}
  
  # Environment Configuration
  ENVIRONMENT: {{ required "Environment name is required" .Values.secrets.environment | b64enc | quote }}
  LOG_LEVEL: {{ required "Log level is required" .Values.secrets.logLevel | b64enc | quote }}
  
  # Additional Security Headers
  SECURE_HEADERS: {{ include "web.secureHeaders" . | b64enc | quote }}
  
  # Rate Limiting Configuration
  RATE_LIMIT_WINDOW: {{ .Values.secrets.rateLimitWindow | default "15m" | b64enc | quote }}
  RATE_LIMIT_MAX_REQUESTS: {{ .Values.secrets.rateLimitMaxRequests | default "100" | b64enc | quote }}
  
  # Error Reporting Configuration
  ERROR_REPORTING_ENABLED: {{ .Values.secrets.errorReportingEnabled | default "true" | b64enc | quote }}
  ERROR_REPORTING_SAMPLE_RATE: {{ .Values.secrets.errorReportingSampleRate | default "0.1" | b64enc | quote }}
  
  # Security Configuration
  CSRF_TOKEN_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  SESSION_SECRET: {{ randAlphaNum 64 | b64enc | quote }}
  
  # Integration Timeouts
  CLAUDE_API_TIMEOUT: {{ .Values.secrets.claudeApiTimeout | default "30000" | b64enc | quote }}
  LINKEDIN_API_TIMEOUT: {{ .Values.secrets.linkedinApiTimeout | default "10000" | b64enc | quote }}
  
  # Feature Flags
  ENABLE_CACHING: {{ .Values.secrets.enableCaching | default "true" | b64enc | quote }}
  ENABLE_METRICS: {{ .Values.secrets.enableMetrics | default "true" | b64enc | quote }}
  
  # Monitoring Configuration
  METRICS_SAMPLE_RATE: {{ .Values.secrets.metricsSampleRate | default "0.1" | b64enc | quote }}
  TRACING_ENABLED: {{ .Values.secrets.tracingEnabled | default "true" | b64enc | quote }}