apiVersion: v2
name: data-service
version: 1.0.0
appVersion: 1.0.0
description: Production-grade Helm chart for LinkedIn Profile Search Data Service - A highly available Spring Boot application providing secure profile storage, data partitioning, and comprehensive data management capabilities with multi-AZ deployment support
type: application

keywords:
  - data-service
  - profile-storage
  - spring-boot
  - high-availability
  - linkedin-search

home: https://github.com/organization/linkedin-profile-search
sources:
  - https://github.com/organization/linkedin-profile-search/tree/main/infrastructure/helm/data-service

maintainers:
  - name: Platform Team
    email: platform@organization.com

annotations:
  deployment.kubernetes.io/preferred-version: "1.27+"
  security.organization.com/compliance-validated: "true"
  backup.organization.com/schedule: "daily"
  monitoring.organization.com/grafana-dashboard: "data-service-prod"

dependencies:
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
      - persistence