# Kubernetes Secret template for LinkedIn Profile Search Service
# Helm v3.12+, Kubernetes v1.27+
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "search-service.fullname" . }}
  labels:
    {{- include "search-service.labels" . | nindent 4 }}
  annotations:
    # Indicate that this secret contains sensitive API credentials
    security.kubernetes.io/sensitive-data: "true"
    # Add timestamp for secret rotation tracking
    timestamp: {{ now | quote }}
type: Opaque
data:
  # LinkedIn API Credentials - Required for authentication
  # Base64 encoded from values.yaml
  LINKEDIN_API_CREDENTIALS: {{ .Values.linkedin.credentials | b64enc | quote }}
  LINKEDIN_API_TOKEN: {{ .Values.linkedin.token | b64enc | quote }}

  # LinkedIn API Configuration
  # Version and Base URL with defaults
  LINKEDIN_API_VERSION: {{ .Values.linkedin.apiVersion | default "v2" | b64enc | quote }}
  LINKEDIN_API_BASE_URL: {{ .Values.linkedin.baseUrl | default "https://api.linkedin.com" | b64enc | quote }}

  # Rate Limiting Configuration
  # Controls API request throttling
  LINKEDIN_API_RATE_LIMIT_CALLS: {{ .Values.linkedin.rateLimit.calls | default 100 | toString | b64enc | quote }}
  LINKEDIN_API_RATE_LIMIT_PERIOD: {{ .Values.linkedin.rateLimit.period | default 60 | toString | b64enc | quote }}

  # Request Timeout Configuration
  # Global timeout for API requests in seconds
  LINKEDIN_API_TIMEOUT: {{ .Values.linkedin.timeout | default 30 | toString | b64enc | quote }}

  # Retry Configuration
  # Exponential backoff settings for failed requests
  LINKEDIN_API_RETRY_MAX_ATTEMPTS: {{ .Values.linkedin.retry.maxAttempts | default 3 | toString | b64enc | quote }}
  LINKEDIN_API_RETRY_INITIAL_DELAY: {{ .Values.linkedin.retry.initialDelay | default 1 | toString | b64enc | quote }}
  LINKEDIN_API_RETRY_MAX_DELAY: {{ .Values.linkedin.retry.maxDelay | default 10 | toString | b64enc | quote }}