{{/* MongoDB Secret Template */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    # Enable automatic secret rotation every 30 days
    secret.kubernetes.io/rotation-enabled: "true"
    secret.kubernetes.io/rotation-interval: "720h"
    # Checksum to trigger pod restarts when config changes
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    # AWS KMS integration for key management
    {{- if .Values.externalSecrets.awsKms.enabled }}
    aws-kms-key-id: {{ .Values.externalSecrets.awsKms.keyId }}
    {{- end }}

type: Opaque

data:
  {{/* Root Password */}}
  {{- if .Values.auth.rootPassword }}
  mongodb-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- else }}
  {{- $rootPassword := randAlphaNum 32 }}
  mongodb-root-password: {{ $rootPassword | b64enc | quote }}
  {{- end }}

  {{/* Replica Set Key */}}
  {{- if .Values.auth.replicaSetKey }}
  mongodb-replica-set-key: {{ .Values.auth.replicaSetKey | b64enc | quote }}
  {{- else }}
  {{- $replicaSetKey := randAlphaNum 756 }} {{/* MongoDB requires minimum 6 and maximum 1024 character key length */}}
  mongodb-replica-set-key: {{ $replicaSetKey | b64enc | quote }}
  {{- end }}

  {{/* TLS Configuration */}}
  {{- if .Values.tls.enabled }}
  {{- if .Values.tls.cert }}
  mongodb-tls-cert: {{ .Values.tls.cert | b64enc | quote }}
  {{- end }}
  {{- if .Values.tls.key }}
  mongodb-tls-key: {{ .Values.tls.key | b64enc | quote }}
  {{- end }}
  {{- if .Values.tls.ca }}
  mongodb-tls-ca: {{ .Values.tls.ca | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{/* Additional Authentication Secrets */}}
  {{- if .Values.auth.usernames }}
  {{- range $index, $username := .Values.auth.usernames }}
  mongodb-user-{{ $index }}: {{ $username | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.auth.passwords }}
  {{- range $index, $password := .Values.auth.passwords }}
  mongodb-password-{{ $index }}: {{ $password | b64enc | quote }}
  {{- end }}
  {{- end }}

{{/* Validation */}}
{{- if and .Values.tls.enabled (not (and .Values.tls.cert .Values.tls.key .Values.tls.ca)) }}
{{- fail "When TLS is enabled, cert, key, and ca must be provided" }}
{{- end }}

{{- if and .Values.auth.enabled (not (or .Values.auth.rootPassword .Values.auth.existingSecret)) }}
{{- fail "Either rootPassword or existingSecret must be provided when auth is enabled" }}
{{- end }}