# Redis Secret template for storing authentication credentials and TLS certificates
# Version: 1.0.0
# This secret is consumed by the Redis StatefulSet for secure credential management
apiVersion: v1
kind: Secret
metadata:
  # Use helper template to generate consistent name with release prefix
  name: {{ include "redis.fullname" . }}-secret
  # Use helper template to generate consistent labels
  labels: {{ include "redis.labels" . }}
type: Opaque
data:
  # Base64 encode the Redis password from values.yaml
  # Required for Redis authentication
  redis-password: {{ .Values.config.redisPassword | b64enc }}
  
  # Optional TLS key and certificate
  # Only included if TLS is configured in values.yaml
  {{- if .Values.config.tlsKey }}
  redis-tls-key: {{ .Values.config.tlsKey | b64enc }}
  {{- end }}
  {{- if .Values.config.tlsCert }}
  redis-tls-cert: {{ .Values.config.tlsCert | b64enc }}
  {{- end }}