# Redis Service Template
# Version: Redis 7.0+
# Purpose: Exposes Redis cache instances for internal cluster access
# Supports: Master-replica setup for high availability

apiVersion: v1
kind: Service

metadata:
  # Use helper template for consistent naming across the release
  name: {{ include "redis.fullname" . }}
  # Apply standard labels from helper template
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  # Apply user-provided service annotations if any
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  # Service type from values (typically ClusterIP for internal access)
  type: {{ .Values.service.type }}
  
  ports:
    # Redis standard port configuration
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  
  # Use consistent selector labels from helper template
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}