apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "analysis-service-claude-api" | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "analysis-service.name" . }}
    helm.sh/chart: {{ include "analysis-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # Add timestamp annotation for tracking secret creation/updates
    timestamp: {{ now | date "2006-01-02T15:04:05Z" }}
    # Add checksum annotation to trigger pod restarts when secret changes
    checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    # Add custom annotations from values.yaml if provided
    {{- if .Values.secrets.annotations }}
    {{- toYaml .Values.secrets.annotations | nindent 4 }}
    {{- end }}
type: Opaque
data:
  # Base64 encode the Claude API key
  {{ .Values.secrets.claudeApiKey.key }}: {{ required "Claude API key is required" .Values.secrets.claudeApiKey.name | b64enc }}
  
  # Add creation timestamp for auditing
  created-at: {{ now | date "2006-01-02T15:04:05Z" | b64enc }}
  
  # Add secret version for tracking rotations
  version: {{ .Chart.Version | default "0.1.0" | b64enc }}

  # Add environment identifier
  environment: {{ .Release.Namespace | b64enc }}