# Helm chart for LinkedIn Profile Search Service
# Version: 1.0.0
# Requires Kubernetes: >=1.27.0
# Dependencies:
# - redis: 17.8.5 (https://charts.bitnami.com/bitnami)
# - mongodb: 13.9.3 (https://charts.bitnami.com/bitnami)

apiVersion: v2
name: search-service
description: Production-grade LinkedIn Profile Search Service for automated candidate sourcing with high availability and scalability
type: application
version: 1.0.0
appVersion: 1.0.0

# Kubernetes version compatibility
kubeVersion: ">=1.27.0"

# Chart keywords for search and categorization
keywords:
  - linkedin
  - search
  - profile
  - recruitment
  - high-availability
  - scalable
  - production

# Chart maintainers
maintainers:
  - name: DevOps Team
    email: devops@company.com
    url: https://github.com/company/search-service

# Template engine
engine: gotpl

# Production dependencies
dependencies:
  - name: redis
    version: 17.8.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cache
      - production

  - name: mongodb
    version: 13.9.3
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
    tags:
      - database
      - production