# Istio Configuration Values for LinkedIn Profile Search and Analysis System
# Version: 1.20+

# Gateway configuration for handling ingress traffic
gateways:
  name: linkedin-gateway
  labels:
    app: linkedin-search
    component: gateway
    version: v1
  ports:
    # HTTP port (will be redirected to HTTPS)
    - name: http
      port: 80
      protocol: HTTP
    # HTTPS port for secure traffic
    - name: https
      port: 443
      protocol: HTTPS
  tls:
    mode: SIMPLE
    credentialName: linkedin-tls-cert
    minProtocolVersion: TLSV1_3
    # Strong cipher suites for enhanced security
    cipherSuites:
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384

# VirtualService configuration for traffic routing
virtualServices:
  name: linkedin-routes
  labels:
    app: linkedin-search
    component: virtualservice
    version: v1
  hosts:
    - api.linkedin-search.com
  routes:
    # Search service routing configuration
    search:
      prefix: /api/v1/search
      service: search-service
      port: 80
      timeout: 30s
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted
      faultInjection:
        delay:
          percentage:
            value: 0.1
          fixedDelay: 5s
    
    # Analysis service routing configuration
    analysis:
      prefix: /api/v1/analysis
      service: analysis-service
      port: 80
      timeout: 60s
      retries:
        attempts: 2
        perTryTimeout: 5s
        retryOn: connect-failure,refused-stream,unavailable,cancelled,resource-exhausted
    
    # API Gateway routing configuration
    api:
      prefix: /api/v1
      service: api-gateway-service
      port: 80
      timeout: 15s
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: connect-failure,refused-stream,unavailable

# DestinationRule configuration for traffic policies
destinationRules:
  name: linkedin-traffic-policy
  labels:
    app: linkedin-search
    component: destinationrule
    version: v1
  trafficPolicy:
    # Load balancing configuration
    loadBalancer:
      simple: ROUND_ROBIN
      consistentHash:
        httpHeaderName: x-user-id
    
    # Connection pool settings
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 5s
        tcpKeepalive:
          time: 7200s
          interval: 75s
      http:
        http1MaxPendingRequests: 1024
        maxRequestsPerConnection: 10
        maxRetries: 3
        idleTimeout: 15s
        h2MaxRequests: 1000
    
    # Circuit breaking configuration
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
      minHealthPercent: 50
    
    # mTLS configuration for service-to-service communication
    tls:
      mode: ISTIO_MUTUAL
      sni: "*.linkedin-search.svc.cluster.local"
  
  # Service subsets configuration
  subsets:
    - name: v1
      labels:
        version: v1
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN