# Chart.yaml for LinkedIn Profile Search and Analysis System Ingress Controller
# Version: 1.0.0
# Provides enterprise-grade ingress management with advanced security features

apiVersion: v2
name: ingress
version: 1.0.0
appVersion: "1.0.0"
description: Enterprise-grade Helm chart for managing ingress traffic with NGINX, advanced WAF protection, automated TLS management, and high availability configuration for the LinkedIn Profile Search and Analysis System
type: application

# Chart Dependencies
dependencies:
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
    tags:
      - ingress
      - loadbalancer
      - waf

  - name: cert-manager
    version: 1.12.3
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
    tags:
      - certificates
      - tls
      - security

# Chart Maintainers
maintainers:
  - name: DevOps Team
    email: devops@example.com
    url: https://github.com/organization/linkedin-profile-search

# Search Keywords
keywords:
  - ingress
  - nginx
  - tls
  - load-balancer
  - waf
  - security
  - high-availability
  - enterprise
  - linkedin-profile-search

# ArtifactHub Annotations
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "true"