# Kubernetes Secret template for data-service credentials
# Version: v1
# Manages sensitive configuration including database credentials, JWT tokens and encryption keys
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "data-service.name" . }}
    helm.sh/chart: {{ include "data-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: data-service
    app.kubernetes.io/part-of: linkedin-profile-search
  annotations:
    # Enable automatic secret mounting in pods
    secret.kubernetes.io/auto-mount: "true"
    # Track last rotation timestamp
    secret.kubernetes.io/last-rotated: {{ now | date "2006-01-02T15:04:05Z07:00" }}
    # Add checksum annotation for triggering pod restarts on secret updates
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    # Add annotations for external secret management integration
    secret.kubernetes.io/managed-by: "helm"
    secret.kubernetes.io/type: "kubernetes.io/opaque"

# Secret type for generic key-value pairs
type: Opaque

# Base64 encoded secret data
data:
  # PostgreSQL credentials
  DB_USER: {{ .Values.postgresql.username | b64enc }}
  DB_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  
  # MongoDB credentials  
  MONGODB_USER: {{ .Values.mongodb.username | b64enc }}
  MONGODB_PASSWORD: {{ .Values.mongodb.password | b64enc }}
  
  # Redis password
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
  
  # JWT authentication secret
  JWT_SECRET: {{ .Values.security.jwt.secret | b64enc }}
  
  # Data encryption key
  ENCRYPTION_KEY: {{ .Values.security.encryption.key | b64enc }}
  
  # Additional connection parameters
  DB_CONNECTION_PARAMS: {{ printf "sslmode=verify-full&sslcert=/etc/certs/client-cert.pem" | b64enc }}
  MONGODB_CONNECTION_PARAMS: {{ printf "ssl=true&replicaSet=rs0&authSource=admin" | b64enc }}
  REDIS_CONNECTION_PARAMS: {{ printf "ssl=true&timeout=5s" | b64enc }}