# API Gateway Helm Chart
# Version: 1.0.0
# Provides production-grade deployment configuration for the LinkedIn Profile Search API Gateway
# with integrated service mesh, monitoring, and caching capabilities

apiVersion: v2
name: api-gateway
description: Production-grade API Gateway service for the LinkedIn Profile Search and Analysis System with integrated service mesh, monitoring, and caching capabilities
type: application
version: 1.0.0
appVersion: "1.0.0"

# Keywords for chart discovery and categorization
keywords:
  - api-gateway
  - nodejs
  - express
  - microservices
  - linkedin-search
  - service-mesh
  - monitoring

# Chart maintainers
maintainers:
  - name: DevOps Team
    email: devops@linkedin-search.com

# Engine compatibility
engine:
  node: ">=18.0.0"

# Required Helm chart dependencies
dependencies:
  # Redis for rate limiting, session management and caching
  # bitnami/redis v17.11.3
  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cache
      - session-store

  # Istio service mesh base components
  # istio/base v1.20.0
  - name: istio-base
    version: 1.20.0
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
    tags:
      - service-mesh
      - security

  # Prometheus monitoring stack
  # prometheus-community/prometheus v25.8.0
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
    tags:
      - monitoring
      - metrics